version: '3'
services:
  postgres:
    container_name: contatinhos-pg
    image: postgres:16-alpine
    restart: always
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: contatinhos
    ports:
      - 5432:5432

volumes:
  pgdata: